### ISSUE TITLE
Areas aren't protected

### ISSUE THREAD

**Issue by mote166** [kenygamer/iProtector-v4.0#2]
When i flag an are with (edit = false + touch = false) it should prevent players from breaking/placing/touching blocks in that specific are but its not working.. heres the config and the areas files:

Config:
```
# Config file for iProtector v4.0 by Kevin Andrews;
# Forked from the original LDX-MCPE/iProtector repository, implementing new features
# and PocketMine-MP API 3.0.0 compatibility

# Settings
Settings:

 # Choose whether enable or disable this plugin
 Enable: true
 
 # Choose whether enable or disable the JSON pretty print area saving setting
 JPP: true

# Messages for protected areas:
Messages:

 # No permission to place that block
 Place:
  Enable: true
  Message: 'You do not have permission to place your {block}!'
 
 # No permission to break that block
 Break:
  Enable: true
  Message: 'You do not have permission to break my {block}!'
 
 # No permission to touch that block or activate things like chests
 Touch:
  Enable: true
  Message: 'You do not have permission to touch my {block}!'
 
 # No permission to hurt other players
 Hurt:
  Enable: false
  Message: 'You do not have permission to hurt {player}!'
 
# Settings for unprotected areas in worlds without specific settings:
Default:

  # Keep players from getting hurt?
  God: false

  # Keep players from editing the world?
  Edit: false
  
  # Protect against TNT and Creeper explosions?
  TNT: false

  # Keep players from touching blocks and activating things like chests?
  Touch: false

# Settings for unprotected areas in individual worlds:
Worlds:

  tr1:

    # Keep players from getting hurt?
    God: false

    # Keep players from editing the world?
    Edit: false
    
    # Protect against TNT and Creeper explosions?
    TNT: false

    # Keep players from touching blocks and activating things like chests?
    Touch: false
```

Areas:

```
 "name": "1",
        "flags": {
            "edit": false,
            "god": true,
            "tnt": false,
            "touch": false
```
